image: python:3.7

variables:
  GIT_SUBMODULE_STRATEGY: recursive

stages:
  - static
  - test

black:
  stage: static
  before_script:
    - pip install black
  script:
    - black --check ./

unittest:
  stage: test
  before_script:
    - pip install poetry
    - poetry install
    - export PYTHONPATH=$PYTHONPATH:./src
  script:
    - poetry run python -m unittest -v
